name: Hprofile Actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: Test workflow
        uses: actions/checkout@v4
      - name: Maven test
        run: mvn test
      - name: checkstyle
        run: checkstyle:checksyle

