name: Hprofile Actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code checkout
        uses: actions/checkout@v4
      - name: Maven test
        run: mvn test
      - name: checkstyle
        run: mvn checkstyle:checkstyle
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

