name: Hprofile Actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code checkout
        uses: actions/checkout@v4
        run: echo ${{GITHUB_WORKSPACE}}
      - name: Maven test
        run: mvn test
      - name: checkstyle
        run: mvn checkstyle:checkstyle
    # Setup Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
    # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
    # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONAR_URL }}
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
           -Dsonar.sources=$GITHUB_WORKSPACE